name: control_asistencia_app
description: app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  http: ^1.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg_splash.png
    - assets/bg_login.png
    - assets/logo.png
